urfuwo/hlx-test

- blocks/article-list/article-list.css
- blocks/article-list/article-list.js
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/tags/cloud
- After: https://dynamic-articles--hlx-test--urfuwo.hlx.live/tags/cloud
- After: https://dynamic-articles--hlx-test--urfuwo.hlx.live/topics/customer
> chore: support dynamic article lists for tags & topics

- scripts/scripts.js
fix: disabled & removed autoblocking
Fix #33
Test URLs:
- After: https://33-disable-hero-autoblocking--hlx-test--urfuwo.hlx.live/blog/2023/11/supply-chain-issues-keeping-ceos-up-at-night
> Disable and remove autoblocking

- blocks/related-articles/related-articles.css
- scripts/scripts.js
- templates/article/article.css
- templates/article/article.js
Test URLs:
- After: https://template-loading--hlx-test--urfuwo.hlx.live/blog/2023/11/supply-chain-issues-keeping-ceos-up-at-night
> fix: template loading (and some styles)

- blocks/title-banner/title-banner.css
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/author/aarongreen
- After: https://title-banner--hlx-test--urfuwo.hlx.live/author/aarongreen
> title-banner (preliminary block + author styling)

- templates/article/article.js
fix: repaired the first paragraph highlighting on blog page
Fix #41
Test URLs:
- After: https://41-blog-highlight-first-paragraph-again--hlx-test--urfuwo.hlx.live/blog/2023/11/supply-chain-issues-keeping-ceos-up-at-night
> Repaired the first paragraph highlighting

- tools/taxonomy/example.json
- tools/taxonomy/taxonomy.js
- tools/taxonomy/taxonomy.json
Test URLs:
- After: https://taxonomyv2--hlx-test--urfuwo.hlx.live/blog/2023/11/supply-chain-issues-keeping-ceos-up-at-night
> Update taxonomy with an example

- scripts/scripts.js
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/2023/12/2023-hasso-plattner-founders-award-finalists-products-and-technology
- After: https://video-decoration--hlx-test--urfuwo.hlx.live/blog/2023/12/2023-hasso-plattner-founders-award-finalists-products-and-technology
> decorate video links

- fstab.yaml
Fix #<gh-issue-id>
Test URLs:
- After: https://--hlx-test--urfuwo.hlx.live/blog/2023/11/supply-chain-issues-keeping-ceos-up-at-night
> authors templating

- fstab.yaml
Fix #<gh-issue-id>
Test URLs:
- After: https://--hlx-test--urfuwo.hlx.live/blog/2023/11/supply-chain-issues-keeping-ceos-up-at-night
> author-templating

- blocks/title-banner/title-banner.js
Fix #46 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/author/aarongreen
- After: https://metadata-authors--hlx-test--urfuwo.hlx.live/author/aarongreen
> Metadata authors

- blocks/article-tags/article-tags.css
- blocks/article-tags/article-tags.js
- scripts/scripts.js
- templates/article/article.css
- templates/article/article.js
Fix #55
Test URLs:
- After: https://article-tags--hlx-test--urfuwo.hlx.live/blog/2023/11/supply-chain-issues-keeping-ceos-up-at-night
> chore: implement tag cloud for article page

- .hlxignore
- README.md
- docs/index.md
> Update .hlxignore to exclude /docs

- blocks/article-list/README.md
- blocks/article-list/article-list.css
- blocks/article-list/article-list.js
- blocks/related-articles/related-articles.js
- styles/styles.css
Format the article card according to figma designs
Fix #69
Test URLs:
- After: https://69-article-card--hlx-test--urfuwo.hlx.live/blog/2023/11/supply-chain-issues-keeping-ceos-up-at-night
Before:
After:
> 69-article-card

- blocks/header/header.css
- blocks/header/header.js
- styles/styles.css
Fix #83 
Test URLs:
- After: https://83-header-iteration-2--hlx-test--urfuwo.hlx.page/draft/skhare/best-time-to-be-a-developer-is-now
> Addressing review comments of issue #83

- styles/styles.css
Fix #93 (partially)
Test URLs:
- After: https://margins--hlx-test--urfuwo.hlx.live/blog/2023/11/supply-chain-issues-keeping-ceos-up-at-night
> chore: Align global margins and gutters with spec

- blocks/article-list/article-list.css
- blocks/article-list/article-list.js
Fix #86
Test URLs:
- After: https://84-article-card-refinement--hlx-test--urfuwo.hlx.live/blog/2023/11/supply-chain-issues-keeping-ceos-up-at-night
> article card refinement

- blocks/footer/footer.css
Fix #93 (partially)
Test URLs:
- After: https://footer-margins--hlx-test--urfuwo.hlx.live/blog/2023/11/supply-chain-issues-keeping-ceos-up-at-night
> chore: Adjust footer margins as per breakpoints in spec

- .github/pull_request_template.md
Fix #<gh-issue-id>
Test URLs:
- After: https://blocklib-inputs--hlx-test--urfuwo.hlx.live/blog/2023/11/supply-chain-issues-keeping-ceos-up-at-night
> Add block library inputs to PR template

- .github/pull_request_template.md
- blocks/link-group/link-group.css
- blocks/social/social.css
- blocks/social/social.js
Fix #113 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/draft/satyam/ai-act-dont-hesitate
- After: https://social--hlx-test--urfuwo.hlx.page/draft/satyam/ai-act-dont-hesitate
Variation Name    | Documentation| Library …
> Generalize 'social' block

- blocks/article-list/article-list.js
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/2023/12/being-human-in-the-age-of-ai
- After: https://fix-cards--hlx-test--urfuwo.hlx.live/blog/2023/12/being-human-in-the-age-of-ai
- Tags: https://fix-cards--hlx-test--urfuwo.hlx.live/tags/ai
For e.g. hero (light)  | …
> fix: cards

- blocks/article-tags/article-tags.css
- blocks/article-tags/article-tags.js
Fix #118
Test URLs:
- After: https://tag-list--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
Article Tags | [doc-link](https://sap.sharepoint.com/:w:/r/sites/207899/_layouts/15/Doc.aspx?sourcedoc=%7B2531D206-227E-4A60-A776-58FD89556DB1%7D&file=article-tags.docx&action=default&mobileredirect=true) | [Library Link](https://tag-list--hlx-test--urfuwo.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/article-tags&index=0)
> chore: style article tag pile's

- blocks/hero/hero.js
Test URLs:
- After: https://hero-null-safe--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
For e.g. hero (light)  | …
> fix: Add null safety in hero block

- blocks/hero/hero.css
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/news/0000/sap-source-to-pay-strategy-focuses-customer-success
- After: https://hero-1600--hlx-test--urfuwo.hlx.live/news/0000/sap-source-to-pay-strategy-focuses-customer-success
For e.g. hero (light)  | …
> fix: Hero container gets 0 width for >1600px screen width

- blocks/article-footnote/article-footnote.css
- blocks/footnote/footnote.css
Fix #143
Test URLs:
- After: https://143-footnote-block--hlx-test--urfuwo.hlx.page/news/0000/the-article
- Test 2: https://143-footnote-block--hlx-test--urfuwo.hlx.page/news/2024/02/sap-further-strengthens-ai-focus-dedicated-growth-area
article-footnote | [doc-link](https://sap.sharepoint.com/:w:/r/sites/207899/_layouts/15/doc.aspx?sourcedoc=%7B02046f1e-8c45-40a3-b153-44cb88e40bdd%7D&action=edit) | [Library Link](https://143-footnote-block--hlx-test--urfuwo.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/article-footnote&index=0)
> Article Footnote block

- blocks/quote/quote.css
fix: multi-line quote
Fix #172
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/2023/02/international-womens-day-2023-empathy-is-our-superpower-to-embrace-equity
- After: https://172-multi-line-quotes-show-in-same-line--hlx-test--urfuwo.hlx.live/blog/2023/02/international-womens-day-2023-empathy-is-our-superpower-to-embrace-equity
> Fixes multi-line quote

- templates/article/article.css
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/2023/02/international-womens-day-2023-empathy-is-our-superpower-to-embrace-equity
- After: https://order-based-grid--hlx-test--urfuwo.hlx.live/blog/2023/02/international-womens-day-2023-empathy-is-our-superpower-to-embrace-equity
> chore: Changed grid-area to order based layout

- templates/article/article.css
Fix #182 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/news/0000/the-article-new
- After: https://182-adapt-article-styles--hlx-test--urfuwo.hlx.page/news/0000/the-article-new
Additional URL (was broken before) https://182-adapt-article-styles--hlx-test--urfuwo.hlx.page/draft/benp/153-sections-with-backgrounds-and-borders
> Adjust grid to allow unknown number of sections

- blocks/author-profile/author-profile.css
- blocks/author-profile/author-profile.js
fix: author-profile
Fix #119 
Test URLs:
- After: https://119-author-profile-block-for-article-pages--hlx-test--urfuwo.hlx.page/news/0000/the-article
Supports three levels of authors:
- author with a structured profile page: example: /author/thomassaueressig
-- blog page: https://119-author-profile-block-for-article-pages--hlx-test--urfuwo.hlx.live/blog/2023/12/being-human-in-the-age-of-ai
-- author profile page: https://sap.sharepoint.com/:w:/r/sites/207899/Shared%20Documents/website/author/thomassaueressig.docx?d=w5fb3d75096a54208b9727578ba243c1a&csf=1&web=1&e=gXyTGp
-- index:description is being used as the author description
- author with a simple profile page: example: /author/luistrunkdeflores
-- author profile …
> Author Profile

- blocks/article-list/article-list.js
- blocks/contact/contact.css
- blocks/contact/contact.js
- blocks/footer/footer.js
- blocks/header/header.js
- blocks/social/social.js
Fix #214
Test URLs:
- After: https://fix-social-icons--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
> fix: accessibility issues for links & imgs

- blocks/article-list/article-list.js
Fix #146
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/news/
- After: https://146-manual-content-list--hlx-test--urfuwo.hlx.live/news/
Newly added article-list to library for this case.
> if `article list` block has links, use these instead of a context filter

- scripts/aem.js
- scripts/scripts.js
- styles/styles.css
Fix #226
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/rootpea/226-article-draft-rootpea
- After: https://226-column-control-style-for-sections--hlx-test--urfuwo.hlx.page/draft/rootpea/226-article-draft-rootpea
Block Name(Section Style Name)    | Documentation | Library Link
column-section | [doc-link](https://sap.sharepoint.com/:w:/r/sites/207899/Shared%20Documents/website/tools/sidekick/blocks/column-section.docx?d=wa06842ecba2a4741bf3b2012739ed336&csf=1&web=1&e=Gh4aaZ) | [Library Link](https://226-column-control-style-for-sections--hlx-test …
> 226 column control style for sections

- styles/styles.css
Fix #226
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/draft/rootpea/219-l1-sample-page
- After: https://column-section-first-item-margin--hlx-test--urfuwo.hlx.page/draft/rootpea/219-l1-sample-page
> chore: remove top margin of first descendant in column section

- blocks/preflight/panels/seo.js
Test URLs:
- After: https://fix-preflight-typo--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
> fix typo preventing preflight checker

- blocks/hero/hero.css
fix: fixed-height hero, two variants:
- fixed height small (450px for M-XL, adaptive height for XS-S). Test URL: https://248-hero-fixed-height--hlx-test--urfuwo.hlx.live/draft/hupe/author/248-juliawhite-fixed-height-small
- fixed height large (550px for M-XL, adaptive height for XS-S). Test URL: https://248-hero-fixed-height--hlx-test--urfuwo.hlx.live/draft/hupe/author/248-juliawhite-fixed-height-large
For comparison: Non-fixed height variant: https://248-hero-fixed-height--hlx-test--urfuwo.hlx.live/author/juliawhite
Specs:
- "Fixed height" means that the height is fixated (for breakpoints M - XL). Editors can choose between two heights: 450px or 550px. These apply to viewports M - XL. For viewports XS and S the height is flexible, i.e., we don't apply any restrictions. Ref: …
> Fixed-height hero banner, 2 variants

- helix-query.yaml
Index change required to fetch description for articles in card list
> chore: Description required for horizontal article cards

- .gitignore
- 404.html
- aemedge/blocks/social/social.js
- aemedge/scripts/aem.js
Test URLs:
- After: https://codebase2--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
> Additional fixes for codebase path changes

- aemedge/scripts/aem.js
Fix #285
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
- After: https://sidenav-null-ref--hlx-test--urfuwo.hlx.page/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
> 285 : chore: Fix null reference in loadSideNav

- aemedge/blocks/contact/contact.css
- aemedge/blocks/contact/contact.js
- aemedge/blocks/footer/footer.js
- aemedge/blocks/header/header.css
Fix icons for correct loading with CDN.
Test URLs:
- After: https://footer-logo-fix--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
> Footer logo & icon fix

- aemedge/blocks/author-profile/author-profile.css
Fix #247 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/blog/2024/01/ai-transformative-moment-business-technology
- After: https://247-styling-issue-fix--hlx-test--urfuwo.hlx.page/blog/2024/01/ai-transformative-moment-business-technology
> styling issue fix

- aemedge/blocks/article-list/article-list.css
- aemedge/blocks/external-links/external-links.css
- aemedge/blocks/header/header.css
- aemedge/blocks/side-nav/side-nav.css
- aemedge/blocks/toc/toc.css
- aemedge/libs/card/card.css
- aemedge/libs/pictureCard/pictureCard.css
Restoring font styles for specific blocks with new CSS variables 
Test URLs:
L3 2 Column
- After: https://font-fix--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
L3 3 column
- Before: https://main--hlx-test--urfuwo.hlx.live/news/0000/the-article
- After: https://font-fix--hlx-test--urfuwo.hlx.live/news/0000/the-article
L1
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/rootpea/219-l1-sample-page
- After: https://font-fix--hlx-test--urfuwo.hlx.live/draft/rootpea/219-l1-sample-page
L2
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/skhare/content-list-test
- After: …
> chore: Restoring fonts

- aemedge/blocks/featured-articles/featured-articles.js
- aemedge/blocks/header/header.css
Fixes
1.  Featured articles not showing due to site root change
2. Jumpy Explore option on header
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/skhare/l1-sample-page
- After: https://fix-featured-articles--hlx-test--urfuwo.hlx.live/draft/skhare/l1-sample-page
> chore: Featured articles not showing

- aemedge/templates/hub/hub.css
Required for #219 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/draft/rootpea/219-l1-sample-page
- After: https://219-background-blue--hlx-test--urfuwo.hlx.page/draft/rootpea/219-l1-sample-page
> 219: re-add style variants: background blue 7 and text white

- aemedge/templates/hub/hub.css
- aemedge/templates/hub/hub.js
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/topics/cloud
- After: https://toggle-sidenav--hlx-test--urfuwo.hlx.page/topics/cloud
Test URLs 2:
- Before: https://main--hlx-test--urfuwo.hlx.page/author/juliawhite
- After: https://toggle-sidenav--hlx-test--urfuwo.hlx.page/author/juliawhite
> chore: Toggle sidenav

- aemedge/blocks/cards/cards.css
- aemedge/blocks/cards/cards.js
Fix #264 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/draft/rootpea/219-l1-sample-page
- After: https://264-cards--hlx-test--urfuwo.hlx.page/draft/rootpea/219-l1-sample-page
For e.g. hero (light)  | [doc-link](https://sap.sharepoint.com/:w:/r/sites/207899/_layouts/15/Doc.aspx?sourcedoc=%7B0B62F23A-5C8F-4C2D-BA2E-C444D3631B51%7D&file=hero.docx&action=default&mobileredirect=true)
> Cards block: add breakpoints, icons variant, grid-n-column variant

- aemedge/blocks/hero/hero.css
- aemedge/templates/hub/hub.css
Tasks:
- rename option "dock to next" to "no bottom space"
- replace real person in Library > Hero with persona, text with lorem ipsum
- remove outdated CSS rule
Fix #299
Test URL dock-to-next => no-bottom-space:
- Before: https://main--hlx-test--urfuwo.hlx.page/draft/hupe/l1/299-no-bottom-space
- After: https://299-hero-minor-reworks--hlx-test--urfuwo.hlx.page/draft/hupe/l1/299-no-bottom-space
Test URL Library > Hero:
- https://main--hlx-test--urfuwo.hlx.live/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/hero&index=5
> Hero minor reworks

- aemedge/scripts/aem.js
In progress button issue , this is not yet xixed raising pull request so that dependent tickets can be worked in parallel 
Fix #237 #238 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/news/0000/the-article
- After: https://237-238-styling-issue-fix--hlx-test--urfuwo.hlx.live/news/0000/the-article
> changed main.js to add wrapper 

- aemedge/blocks/content-list/content-list.css
Fix #265 
Test URLs:
L1
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/skhare/l1-sample-page
- After: https://265-four-columns-content-list--hlx-test--urfuwo.hlx.live/draft/skhare/l1-sample-page
L2 (Unchanged)
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/skhare/content-list-test
- After: https://265-four-columns-content-list--hlx-test--urfuwo.hlx.live/draft/skhare/content-list-test
> bugfix/265:  Content list: default to four columns if there is no side navigation

- aemedge/blocks/cards/cards.css
- aemedge/blocks/cards/cards.js
Fix #323
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/draft/rootpea/hub-l1
- After: https://323-cards-block--hlx-test--urfuwo.hlx.page/draft/rootpea/hub-l1
> 323 - simplify usage of cards link tiles and fix picture sizing

- aemedge/blocks/hero/hero.css
- aemedge/styles/styles.css
- aemedge/templates/hub/hub.css
Fix #307
Test URLs:
L2
- Before: https://main--hlx-test--urfuwo.hlx.page/draft/skhare/content-list-test
- After: https://307-l2-page-hero-left-spacing--hlx-test--urfuwo.hlx.page/draft/skhare/content-list-test
L2, media blend
- Before: https://main--hlx-test--urfuwo.hlx.live/author/juliawhite
- After: https://307-l2-page-hero-left-spacing--hlx-test--urfuwo.hlx.live/author/juliawhite
L1 (Unchanged)
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/skhare/l1-sample-page
- After: https://307-l2-page-hero-left-spacing--hlx-test--urfuwo.hlx.live/draft/skhare/l1-sample-page
L3 (Unchanged)
- Before: https://main--hlx-test--urfuwo.hlx.page/news/2024/01/accelerate-innovation-with-clean-core-strategy
- After: https://307-l2-page-hero-left-spacing--hlx-test--urfuwo.hlx.page/news/2024/01/accelera …
> bugfix/307: Correct left spacing of hero on L2 pages

- aemedge/blocks/header/header.css
Fix #327 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/
- After: https://327-bugs-in-global-nav--hlx-test--urfuwo.hlx.live/blog/
> Adjusted styles to accomodate no text wrap and center flyout menu position

- aemedge/libs/card/card.css
- aemedge/libs/pictureCard/pictureCard.css
- aemedge/templates/hub/hub.css
Fix #328 #329 
Test URLs:
- After: https://329-eyebrow--hlx-test--urfuwo.hlx.live/topics/
> fixing eyebrow font text color and size

- aemedge/blocks/table/table.css
- aemedge/blocks/table/table.js
Relates #336 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/the-c-suite-gets-an-ai-upgrade
- After: https://basic-table--hlx-test--urfuwo.hlx.live/blog/the-c-suite-gets-an-ai-upgrade
> chore: add basic table

- aemedge/blocks/hero/hero.css
fix: add hero background blue 7 and text white
Fix #347
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/tags/sap-erp-hcm
- After: https://347-hero-add-color-background-blue-7--hlx-test--urfuwo.hlx.live/tags/sap-erp-hcm
> Hero: Add background blue/7 and text white

- aemedge/blocks/hero/hero.css
fix: added Indigo/9 to hero
Fix #349
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/tags/sap-erp-hcm
- After: https://349-hero-background-color-indigo9--hlx-test--urfuwo.hlx.live/tags/sap-erp-hcm
> Added Indigo/9 as hero background color

- aemedge/blocks/related-articles/related-articles.js
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/resources/building-the-future-factory-a-special-report
- After: https://article-filter--hlx-test--urfuwo.hlx.live/resources/building-the-future-factory-a-special-report
> chore: trim the tags before comparing

- aemedge/blocks/hero/hero.js
- aemedge/blocks/related-articles/related-articles.js
By specifying 'full background image' for a hero, one can request a loss-less rendition.
fix: 'full background image' will force the image to be rendered in loss-less quality (webpll)
Fix #321
Test URLs (hero will change its quality):
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/hupe/321-pattern-quality
- After: https://321-hero-improve-pattern-quality--hlx-test--urfuwo.hlx.live/draft/hupe/321-pattern-quality
> Hero: Improve pattern quality

- aemedge/styles/styles.css
- Added arrow icon to all links
- Change default color
- Change color on hover
Fix #268 
Test URLs:
- After: https://268-fix-links--hlx-test--urfuwo.hlx.live/topics/
> Added arrow icon to all links

- aemedge/blocks/hero/hero.js
Test URLs:
- After: https://hero-eyebrow-fix--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
- Test 2 https://hero-eyebrow-fix--hlx-test--urfuwo.hlx.live/resources/renewable-energy-challenges
> fix: eyebrow for multiple content types

- aemedge/blocks/content-list/content-list.css
- aemedge/templates/hub/hub.css
Elaine asked for more spacing between the links and the headings within a section on L1 page. 
Test URLs:
- After: https://fix-spacing-L1--hlx-test--urfuwo.hlx.live/topics/
> chore: Fix spacing L1

- aemedge/blocks/header/header.css
Test URLs:
- After: https://fix-flyout-menu--hlx-test--urfuwo.hlx.live/topics/
> chore: Header flyout menu items should stack for single list

- aemedge/styles/styles.css
Test URLs:
- After: https://fix-icons--hlx-test--urfuwo.hlx.live/topics/
> chore: only link should have arrows not buttons/icons

- aemedge/styles/styles.css
Test URLs:
- After: https://fix-button-decoration--hlx-test--urfuwo.hlx.live/topics/
> chore: only buttons in main content must be decorated

- aemedge/blocks/side-nav/side-nav.css
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/
- After: https://fix-side-nav-font--hlx-test--urfuwo.hlx.live/blog/
> match font size of expanding list heading

- aemedge/blocks/accordion/accordion.css
- aemedge/blocks/accordion/accordion.js
Fix #337 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/resources/data-management-glossary
- After: https://337-accordion-basic-block--hlx-test--urfuwo.hlx.live/resources/data-management-glossary
accordion| [doc-link](https://sap.sharepoint.com/:w:/r/sites/207899/_layouts/15/doc.aspx?sourcedoc=%7B90174feb-f4d2-4d94-843e-ebf797733770%7D&action=edit) | [Library Link](https://337-accordion-basic-block--hlx-test--urfuwo.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/accordion&index=1)
> 337: Basic Accordion implementation

- aemedge/blocks/accordion/accordion.css
- aemedge/blocks/accordion/accordion.js
Adding styling for accordion block to match https://sap.frontify.com/document/223143#/-/accordion
There is potentially some additional functionality to be added wrt a container header and "Expand/Collapse All" button. Here we've just focused on styling/behaviour in the body of the accordion.
Fix #337 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/resources/data-management-glossary
- After: https://337-accordion-styling--hlx-test--urfuwo.hlx.live/resources/data-management-glossary
> 337: Accordion Styling

- helix-query.yaml
fix: add design content to index
Fix #400
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/design/stories-resources/ai-is-changing-the-future-of-erp-ux
- After: https://400-design-initial-setup--hlx-test--urfuwo.hlx.live/design/stories-resources/ai-is-changing-the-future-of-erp-ux
> Add /design content to index

- aemedge/templates/article/article.css
- aemedge/templates/article/article.js
Fix #388
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/rjwtrmn/the-article-copy
- After: https://388-centre-small-images-l3--hlx-test--urfuwo.hlx.live/draft/rjwtrmn/the-article-copy
> 388: Group L3 article picture and caption together and centre.

- aemedge/blocks/hero/hero.css
fix: show hero avatar image in correct circular shape
Fix #416
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/blog/2023/12/being-human-in-the-age-of-ai
- After: https://416-hero-avatar-round--hlx-test--urfuwo.hlx.live/blog/2023/12/being-human-in-the-age-of-ai
Ref: https://adobe-dx-support.slack.com/archives/C05JM4HS24E/p1712138818232039
> Show hero avatar image in correct aspect ratio

- aemedge/libs/avatar/avatar.js
chore: push the 410 code again
Fix #437
Test URLs:
- After: https://437-second-attempt-410--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
> Push 410 code changes one more time

- aemedge/blocks/author-profiles/author-profiles.js
- aemedge/blocks/hero/hero.js
- aemedge/libs/avatar/avatar.css
- aemedge/libs/avatar/avatar.js
- aemedge/libs/pictureCard/pictureCard.js
chore: push all five 410 files again
Fix #439 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/2023/12/being-human-in-the-age-of-ai
- After: https://439-force-entire-410-code-change-again--hlx-test--urfuwo.hlx.live/blog/2023/12/being-human-in-the-age-of-ai
> Push all files changed in 410 again

- aemedge/blocks/side-nav/side-nav.css
- aemedge/blocks/side-nav/side-nav.js
Fix #425
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/design/design-system
- After: https://425-highlight-current-page-nav--hlx-test--urfuwo.hlx.live/design/design-system
> 425: Highlight link to current page if it appears in side nav.

- aemedge/blocks/content-list/content-list.css
Fix #425
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/design/
- After: https://425-content-list-wide--hlx-test--urfuwo.hlx.live/design/
(Also made a change to add top padding when wrapped in section with coloured background, ignore issue with hero margin, fix for that on the way)
- Before: https://main--hlx-test--urfuwo.hlx.live/design/stories-resources/
- After: https://425-content-list-wide--hlx-test--urfuwo.hlx.live/design/stories-resources/
Variation Name    | 
------------- | 
content list (wide)  |
> 425: Content list wide variant

- aemedge/styles/styles.css
Fix #390
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/rjwtrmn/the-article-copy
- After: https://390-additional-reading--hlx-test--urfuwo.hlx.live/draft/rjwtrmn/the-article-copy
Variation Name    | Library Link
For e.g. section (additional reading)  | [lib-link](https://390-additional-reading--hlx-test--urfuwo.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/section-styles&index=3)
> 390: Additional reading styles

- aemedge/styles/styles.css
Small padding fix. (Accidentally swapped block and inline paddings)
> 390: Additional reading, small fix

- tools/sitemap/package.json
> removed deprecated dependency

- .eslintrc.js
> #480 Added Windows CRLF support to eslintrc.js

- .github/pull_request_template.md
- README.md
- aemedge/blocks/design-system-footer/design-system-footer.css
- aemedge/blocks/design-system-footer/design-system-footer.js
- aemedge/blocks/design-system-header/design-system-header.css
- aemedge/blocks/design-system-header/design-system-header.js
- aemedge/scripts/scripts.js
Fix #479 
Test URLs:
After: https://issue-479--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
**Design system:**
Before: https://main--hlx-test--urfuwo.hlx.live/design-system/fiori-design-web/button
After: https://issue-479--hlx-test--urfuwo.hlx.live/design-system/fiori-design-web/button
Not adding extra info as the blocks are footer and header (not meant to be used by authors)
design-system-header | - | -
design-system-footer | - | -
Variation Name    | …
> Issue 479 - Initial technical set up

- aemedge/scripts/scripts.js
Fix #411
Test URLs:
Before: https://main--hlx-test--urfuwo.hlx.live/tags/carbon-footprint
After: https://411-page-speed-fix--hlx-test--urfuwo.hlx.live/tags/carbon-footprint
> 411: Add null check.

- aemedge/blocks/hero/hero.css
- aemedge/blocks/hero/hero.js
- Eyebrow arrow removed
- Content vertically centered to horizontal axis
- Image aspect ratio enforced (16:9)
Fix #497
Test URLs:
L3 (text centered, aspect ratio, eyebrow arrow removed)
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/ext-how-ai-powered-cybersecurity-combats-ai-threats
- After: https://497-hero-media-blend-styling-tweaks--hlx-test--urfuwo.hlx.live/blog/ext-how-ai-powered-cybersecurity-combats-ai-threats
L2 (text centered)
- Before: https://main--hlx-test--urfuwo.hlx.live/topics/sustainability
- After: https://497-hero-media-blend-styling-tweaks--hlx-test--urfuwo.hlx.live/topics/sustainability
L1 (No change)
- After: https://497-hero-media-blend-styling-tweaks--hlx-test--urfuwo.hlx.live/topics/ …
> 497: Hero styling tweaks

- aemedge/blocks/cards/cards.css
- aemedge/blocks/contact/contact.css
- aemedge/blocks/footer/footer.css
- aemedge/blocks/header/header.css
- aemedge/blocks/hero/hero.css
- aemedge/blocks/hero/hero.js
- aemedge/scripts/scripts.js
- aemedge/styles/styles.css
Fix #484
Added universal star selector for box-sizing: border-box (normalization, reset, streamline).
- Before: https://main--hlx-test--urfuwo.hlx.page/design/design-system
- After: https://484-box-sizing-border-box-rebase--hlx-test--urfuwo.hlx.page/design/design-system (looks the same)
> 484 box sizing border box (3)

- .github/pull_request_template.md
- aemedge/scripts/scripts.js
- aemedge/templates/web-component/web-component.css
- aemedge/templates/web-component/web-component.js
First PR for #512 
Test URLs:
After: https://basic-web-component--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
**Design system:**
Before: https://main--hlx-test--urfuwo.hlx.live/fiori-design-web/button-web-component
After: https://basic-web-component--hlx-test--urfuwo.hlx.live/fiori-design-web/button-web-component
> Create web-component template

- aemedge/blocks/content-list/content-list.js
- aemedge/scripts/utils.js
Relates to #391 
Test URLs:
Before: https://main--hlx-test--urfuwo.hlx.live/topics/
After: https://fix-content-list-filters--hlx-test--urfuwo.hlx.live/topics/
> chore: fix filters based on new tagging

- aemedge/blocks/article-list/article-list.js
- fstab.yaml
Relates to #391 
Test URLs:
Before: https://main--hlx-test--urfuwo.hlx.live/topics/retail
After: https://391-template-pages--hlx-test--urfuwo.hlx.live/topics/retail
> chore: fix article-list dynamic URL filters

- fstab.yaml
> fix: fstab.yaml

- aemedge/blocks/hero/hero.js
- aemedge/libs/tag/tag.js
Relates to #391 
Test URLs:
After: https://391-fix-tags--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
> fix: tag list links for news
