urfuwo/hlx-test

- blocks/columns/columns.css
- blocks/header/header.css
- blocks/hero/hero.css
- styles/styles.css
- templates/article/article.css
This is global styling, iteration 1. A lot of design information is missing and has been requested from SAP, see https://github.com/urfuwo/hlx-test/issues/72. When that information becomes available, it will be incorporated using a separate GH issue. Stylings that are based on assumptions have been marked as such.
Note: the header did not render, so I could not validate it. Sorry if I messed up your header, @saurabh-khare
Changes made:
Global styles have been extracted from https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=269-30889&mode=design&t=d8vHtgahsV4EkVVv-0 
Media queries:
Replaced all @media query sizes with 3 UDex breakpoints:
- 640px (--udexGridSMinWidth)
- 980px (--udexGridMMinWidth)
- 1600px (--udexGridXLMinWidth), header only)
Media …
> Global styling iteration 1

- blocks/hero/hero.js
Test URLs:
- Before: https://main-picture--hlx-test--urfuwo.hlx.live/draft/satyam/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
- After: https://hero-picture--hlx-test--urfuwo.hlx.live/draft/satyam/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
For e.g. hero (light)  | …
> chore: Hero (media blend) - Use 'picture' in additionalContent slot

- templates/article/article.css
Main content must be aligned with top nav margins so it does not stretches in 1600px+ layouts  
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/news/0000/sap-source-to-pay-strategy-focuses-customer-success
- After: https://content-layout-on-xl--hlx-test--urfuwo.hlx.page/news/0000/sap-source-to-pay-strategy-focuses-customer-success
> chore: Main content must remain centered on XL devices

- blocks/toc/toc.css
- blocks/toc/toc.js
- scripts/dom-builder.js
- templates/article/article.js
Fix #111
This introduces the side navigation / table of contents for L3 article pages.
As requested, it is a basic version that does not yet track the current position in the page to update the TOC but first focusses on the hash in the url to highlight the active part.
Please provide some feedback on the integration, as it this block renders at the same time as the hero, not subsequently as the remaining page (if that is the desired state?) LHS does not change / improves for desktop compared with the main branch.
Also, where & how do we document blocks that are generated by metadata like this one?
Test URLs:
- After: https://111-in-page-table-of-contents--hlx-test--urfuwo.hlx.page/news/0000/the-article
Block Name    | …
> 111 in page table of contents

- helix-query.yaml
fix: added property description (og:description) from author profile docs to author index
Fix #197 
Changes:
- added column "description" to /authors-index.xlsx
- index definition updated: https://197-author-index-add-description-property--hlx-test--urfuwo.hlx.page/helix-query.yaml - property "description" added to index "author"
Test URLs:
- After: https://197-author-index-add-description-property--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
> Author Index: Add property description

- helix-query.yaml
fix: added author profile doc property "title" to the author index
Fix #201
Test URLs:
- After: https://201-author-index-add-title--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
> Author Index: add author profile doc property 'title' to index

- blocks/quote/quote.js
Fix #169
Supports missing author information / quote only.
Styling is different on the screenshot in Figma, so will probably have to adjusted once available.
Test URLs:
- After: https://169-quote-block-should-have-quote-only-mode--hlx-test--urfuwo.hlx.page/news/0000/the-article
Variation Name    | Documentation   | Library
------------- | ------------- | -------------
Quote without author  | [doc-link](https://sap.sharepoint.com/:w:/r/sites/207899/_layouts/15/Doc.aspx?sourcedoc=%7BA3B64EC2-D52A-4678-9579-CAA9AF162517%7D&file=quote.docx&action=default&mobileredirect=true)  | [Lib](https://169-quote-block-should-have-quote-only-mode--hlx-test--urfuwo.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick …
> Handling quote without author

- .gitignore
- blocks/hero/hero.js
- blocks/preflight/panels/seo.js
- helix-query.yaml
- scripts/schema.js
First part of metadata changes for new imported content.
Relates #200 
Test URLs:
* Before: https://main--hlx-test--urfuwo.hlx.live/blog/2019/06/save-coastal-wildlife-sap-employee-profile
* After: https://fix-for-import--hlx-test--urfuwo.hlx.live/blog/2019/06/save-coastal-wildlife-sap-employee-profile
> chore: adapt for meta data changes

- blocks/article-footnote/article-footnote.css
- blocks/article-footnote/article-footnote.js
- blocks/hero/hero.css
- blocks/hero/hero.js
fix: article-footnote: added published and updated time entries, delimited by dot
fix: hero: added single updated time entry (which uses either modified-time or - as a fallback - published-time)
chore: replaced dot separators in hero with ::after content
Fix #221
Test URLs:
- After: https://221-dates-in-hero-footnote--hlx-test--urfuwo.hlx.live/news/0000/the-article
Validation cases:
- /draft/hupe/221-article-published - only published date is set
- /draft/hupe/221-article-published-updated - published and modified/update dates are set
- /draft/hupe/221-article-updated - only modified/updated date is set
- /draft/hupe/221-article-neither-published-not-updated - neither published nor updated/modified date is set
> Add publication / update dates to hero and footnote

- blocks/author-profile/author-profile.js
- blocks/author-profiles/author-profiles.js
fix: removed fallback role 'Author'
fix: handle empty results: if no entries are returned, don't render anything, both for single author profiles and for author profile lists. Also remove the parent node to ensure it does not take up vertical space
Fix #239
Test URLs for case 1 (remove default role):
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/2023/12/sap-maxattention-serving-cios-business-transformation
- After: https://239-author-profile-issues--hlx-test--urfuwo.hlx.live/blog/2023/12/sap-maxattention-serving-cios-business-transformation
Test URLs for case 2 (don't render anything if no author profiles have been found):
- Before: https://main--hlx-test--urfuwo.hlx.page/blog/2023/04/planalytics-weather-analytics-reduce-food-waste
- After: …
> 239 Remove default role 'Author' and don't render anything if no authors are found

- aemedge/styles/styles.css
Motivation: Add top and bottom padding to the column section element (directly beneath the top hero) on the L1 page
Figma ref: https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=4075-169233&mode=design&t=H9W7a6YSqBaqEf8q-4
Set top and bottom padding of column section, according to https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=4075-169233&mode=design&t=H9W7a6YSqBaqEf8q-4:
XS-S: top: 56, bottom: 40
M: top: 64, bottom: 48
L-XL: top: 84, bottom: 56
Fix #289
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/hupe/l1/289-column-section
- After: https://289-l1-column-section-block-needs-top-spacing--hlx-test--urfuwo.hlx.live/draft/hupe/l1/289-column-section
Note: the template page does not use the L1 …
> L1 - Column section: top and bottom padding

- aemedge/blocks/hero/hero.css
Motivation:
- Implement the hero as needed at the top of L1 pages
- Figma ref: https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=4075-169235&mode=design&t=A7ULffWUtHmo32sM-4
Two features were implemented:
- flexible height hero with a background image that covers the entire hero
- hero can be configured to dock to next element, i.e., not have vertical spacing to the next element
Fix #156 
Fix #288 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/draft/hupe/l1/156-fixed-hero-full-background
- After: https://156-hero-flex-height--hlx-test--urfuwo.hlx.live/draft/hupe/l1/156-fixed-hero-full-background
hero (full background image)  | …
> L1 - flexible height hero with full background image, docks to next element

- aemedge/blocks/hero/hero.css
- aemedge/styles/styles.css
- aemedge/templates/hub/hub.css
Hacky way to restrict hero content. Ideally it must be done by slot variables but they do not expose padding/margins on all axis. 
Fix #220 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/mhaack/hero-demo
- After: https://220-restrict-hero-content--hlx-test--urfuwo.hlx.live/draft/mhaack/hero-demo
> Align hero content with rest of the page

- aemedge/blocks/contact/contact.css
- aemedge/blocks/contact/contact.js
- aemedge/blocks/footer/footer.css
- aemedge/blocks/social/social.css
fix: removed chinese from country selector
fix: L, XL: aligned footer columns at the top with the brand logo and country selector
fix: social media: use single-line table variant
fix: contact: use 18px / 1.125rem icons as specified
fix: links: use black, no underline, same hover color as sidenav
fix: link group headline: adapted font weight (was too bold)
fix: align social icons with rest of contact block on the left
Ref: https://sap.frontify.com/document/223143#/-/footer/usage
Fix #320 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/author/juliawhite
- After: https://320-social-icons-in-footer--hlx-test--urfuwo.hlx.live/author/juliawhite
> Footer changes (Social icons and more)

- aemedge/blocks/hero/hero.js
fix: replace title-banner with hero, part one: Enable hero to handle text placeholders [author] <= metadata('author'), [page] <= adapted path mapped by placeholders
Q: What is part two?
A: Removing title-banner block from the codebase (which can only be done after all pages have been adapted to the hero)
Fix #279
Test URL 1 (Topic page with placeholder text [page] in the hero):
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/hupe/279-topic-template
- After: https://279-author-topic-tag-page-cleanup--hlx-test--urfuwo.hlx.live/draft/hupe/279-topic-template
Test URL 2 (Tag page with placeholder text [page] in the hero):
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/hupe/279-tag-template
- After: https://279-author-topic-tag-page-cleanup--hlx-test--urfuwo.hlx.live/draft/hupe/ …
> Replace title-banner with hero - part I

- aemedge/styles/styles.css
Spacing only applied for H2 & H3
Fix #326 
Test URLs:
- After: https://326-headling-spacing--hlx-test--urfuwo.hlx.live/topics/
> Spacing changed for h2 and h3

- aemedge/blocks/hero/hero.css
Hero section should not add padding as rest of the sections
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/news/2024/03/sap-and-nvidia-to-accelerate-generative-ai-adoption
- After: https://hero-spacing--hlx-test--urfuwo.hlx.page/news/2024/03/sap-and-nvidia-to-accelerate-generative-ai-adoption
> chore: Hero section must not add padding

- aemedge/blocks/hero/hero.js
L3 pages should get an automatic eyebrow text based on the content type, but only if there is non set.
Fix #343
Test URLs:
- After: https://hero-l3--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
> chore: fix eyebrow for L3 hero

- aemedge/styles/styles.css
- aemedge/templates/article/article.css
- aemedge/templates/hub/hub.css
Instead of default padding at bottom of 56px for all sections it is required that first section gets 84px top padding, middle sections with 56px bottom padding and last section gets 84px padding at bottom. This is inline with figma design. 
Test URLs:
L3
- After: https://fix-spacing--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
L2
- Before: https://main--hlx-test--urfuwo.hlx.live/author/jacquelineprause
- After: https://fix-spacing--hlx-test--urfuwo.hlx.live/author/jacquelineprause
L1
- After: https://fix-spacing--hlx-test--urfuwo.hlx.live/topics/
> chore: fixing section spacing for all templates

- aemedge/blocks/hero/hero.css
Fix #346 
Test URLs:
L2 (unchanged)
- Before: https://main--hlx-test--urfuwo.hlx.page/draft/skhare/content-list-test
- After: https://346-xs-s-hero-text-bleeds-into-side-image--hlx-test--urfuwo.hlx.page/draft/skhare/content-list-test
L2, media blend
- Before: https://main--hlx-test--urfuwo.hlx.live/author/juliawhite
- After: https://346-xs-s-hero-text-bleeds-into-side-image--hlx-test--urfuwo.hlx.live/author/juliawhite
L1 (unchanged)
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/skhare/l1-sample-page
- After: https://346-xs-s-hero-text-bleeds-into-side-image--hlx-test--urfuwo.hlx.live/draft/skhare/l1-sample-page
Article page (unchanged)
- Before: https://main--hlx-test--urfuwo.hlx.page/news/2024/01/accelerate-innovation-with-clean-core-strategy
- After: …
> 346: Hero in XS + S: Text bleeds into side image

- aemedge/scripts/delayed.js
- aemedge/scripts/scripts.js
feat: Tracking and Analytics (Adobe Data Collection)
- SAP MVP native data layer implemented
- Launch SAP MVP (News) loaded and beacon fired on PROD (www.sap.com) and QA (main...hlx.live, www-qa.sap.com)
- Disabled on DEV (localhost, ...hlx.page), unless query param 'tr' is specified
Notes:
- To inspect the data layer, use adobeDataLayer.getState() in console
- The term 'AdobeDC' (Adobe Data Collection) and param name 'tr' have been used as users are sensitive to tracking. 'AdobeTags' has been used instead of AdobeLaunch, as it is the product name
- Currently, loading Tags/Launch will cause a lot of errors in the console log (will be addressed on the Analytics side)
Fix #102 
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/2023/12/being-human-in-the-age-of-ai
- After: …
> 102: Analytics and Tracking MVP for News

- aemedge/blocks/author-profile/author-profile.js
- aemedge/blocks/hero/hero.js
- aemedge/libs/avatar/avatar.js
- aemedge/scripts/article.js
fix: add avatar image to hero if available and the number of authors is one
Limitations: The image is not (necessarily) shown as round, which needs to be addressed with the UDex Avatar component team
Fix #292 
Test URL (single author with avatar image):
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/2023/12/being-human-in-the-age-of-ai
- After: https://292-hero-avatar-display-author-picture--hlx-test--urfuwo.hlx.live/blog/2023/12/being-human-in-the-age-of-ai
Test URL (multiple authors, no avatar image shown, unchanged):
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/hupe/224-multiple-authors
- After: https://292-hero-avatar-display-author-picture--hlx-test--urfuwo.hlx.live/draft/hupe/224-multiple-authors
Test URL (no avatar available, unchanged):
- Before: …
> 292 - Hero show avatar image

- aemedge/libs/avatar/avatar.css
- aemedge/libs/avatar/avatar.js
- aemedge/libs/pictureCard/pictureCard.css
- aemedge/libs/pictureCard/pictureCard.js
- aemedge/templates/hub/hub.js
fix: author names should not be clickable in cards (both when an avatar image and when no avatar image is shown)
Fix #442
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/tags/sap-erp-hcm
- After: https://442-card-author-info-non-clickable--hlx-test--urfuwo.hlx.live/tags/sap-erp-hcm > horizonal and vertical cards with and without an avatar image
Test URL 2:
- Before: https://main--hlx-test--urfuwo.hlx.live/topics/ai
- After: https://442-card-author-info-non-clickable--hlx-test--urfuwo.hlx.live/topics/ai
> Author names should not be clickable in cards

- helix-query.yaml
Added a default index for whole content tree to be used in sitemap and other programmatic functions
> chore: Introducing default query index

- aemedge/scripts/scripts.js
fix: reflect user login status in data layer, iteration 1 (for details see ticket #207)
Ref: https://adobe-dx-support.slack.com/archives/C06SB3177F1/p1712591740928939?thread_ts=1712231909.703159&cid=C06SB3177F1
Fix #207 
Test URLs:
- After: https://207-analytics-user-login-status--hlx-test--urfuwo.hlx.page/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
Test case on QA after deployment:
- Register on www-qa.sap.com (header)
- Login on www-qa.sap.com
- Navigate to www-qa.sap.com/blogs/
- Inspect data layer (browser console: adobeDataLayer.getState() > user > loginStatus should be 'yes' when logged in, 'no' when not logged in)
> 207 - Track user login status - iteration 1

- aemedge/blocks/hero/hero.css
- aemedge/templates/article/article.css
- aemedge/templates/hub/hub.css
- Hero background should be continuous with background of following section (i.e. no white margin between sections with colourful backgrounds)
- Spacing between hero content elements should now more closely match the Figma designs.
- Hero text content width should take up more of the space at larger screen sizes as per Figma.
- Vertical hero padding should adjust according to breakpoints (40px -> 48px -> 56px);
Fix #449
Test URLs:
Design Page with hero margin issue
- Before: https://main--hlx-test--urfuwo.hlx.live/design/stories-resources
- After: https://449-hero-bottom-margin--hlx-test--urfuwo.hlx.live/design/stories-resources
L3
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/ext-how-ai-powered-cybersecurity-combats-ai-threats
- After: …
> 449: Hero spacing issues

- aemedge/blocks/fast-facts/fast-facts.css
- aemedge/blocks/fast-facts/fast-facts.js
- aemedge/blocks/quote/quote.css
- aemedge/blocks/quote/quote.js
- aemedge/styles/styles.css
Fix #397
Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/rjwtrmn/fast-facts-text-green
- After: https://397-fast-facts-block--hlx-test--urfuwo.hlx.live/draft/rjwtrmn/fast-facts-text-green
Quote (Moved link styles to common stylesheet)
- Before:  https://main--hlx-test--urfuwo.hlx.live/draft/rjwtrmn/thomassaueressig-copy
- After: https://397-fast-facts-block--hlx-test--urfuwo.hlx.live/draft/rjwtrmn/thomassaueressig-copy
fast facts | [doc-link](https://sap.sharepoint.com/:w:/r/sites/207899/_layouts/15/Doc.aspx?sourcedoc=%7B83C10908-D93C-4948-9B81-DB04034C9DA4%7D&file=fast-facts.docx&action=default&mobileredirect=true) | [Library …
> 397: Fast facts block

- aemedge/blocks/content-list/content-list.css
- aemedge/blocks/featured-articles/featured-articles.css
- aemedge/libs/avatar/avatar.css
- aemedge/libs/pictureCard/pictureCard.css
- Adjust border radius, text sizes, spacing for both vertical and horizontal picture cards (content list and featured articles) to match Frontify more closely (https://sap.frontify.com/document/223143#/-/resource-center) and address issues spotted by Elaine (https://adobe-dx-support.slack.com/archives/C06H8UNQ3RS/p1710798138014269?thread_ts=1710770896.748139&cid=C06H8UNQ3RS).
- Vertical picture card now uses flexbox rather than grid to layout contents, as elements (specifically info box for avatar and readtime/date) can vary in height between cards depending on availability of information).
- Text only cards should not be affected.
Fix #341
Test URLs:
Before: https://main--hlx-test--urfuwo.hlx.live/topics/
After: …
> 341: Picture cards fine alignment and styling tweaks

- aemedge/blocks/article-tags/article-tags.js
- aemedge/blocks/hero/hero.js
- aemedge/blocks/related-articles/related-articles.js
- aemedge/libs/tag/tag.js
- aemedge/scripts/utils.js
- helix-query.yaml
Relates #391 
Change to new single tag fields for tag usage on L3 pages:
* update hero for eyebrow and first tag
* update article tags
* update related article cards
Test URLs:
Before: https://main--hlx-test--urfuwo.hlx.live/news/2020/02/sap-proaxia-intelligent-enterprise-solution-automotive-retail-sap-s-4hana
After: https://feat-391-tagging--hlx-test--urfuwo.hlx.live/news/2020/02/sap-proaxia-intelligent-enterprise-solution-automotive-retail-sap-s-4hana
Test 2: https://feat-391-tagging--hlx-test--urfuwo.hlx.live/news/2020/02/sap-io-foundry-munich-cohort-acceleration-program-marketing-commerce-startups
Test 3: https://feat-391-tagging--hlx-test--urfuwo.hlx.live/blog/2020/02/doehler-goodyear-intelligent-enterprise-sap-s4hana
> chore: rework tags for L3 pages

- aemedge/blocks/hero/hero.js
Small fix to account for no content-type/x returned from metadata.
Fix #500
Test URLs:
Before: https://main--hlx-test--urfuwo.hlx.live/blog/ext-how-ai-powered-cybersecurity-combats-ai-threats
After: https://500-optional-chaining-fix--hlx-test--urfuwo.hlx.live/blog/ext-how-ai-powered-cybersecurity-combats-ai-threats
> 500: Account for pages without content type.

- aemedge/blocks/article-tags/article-tags.js
- aemedge/blocks/hero/hero.js
Filter all internal tags which are either not defined in the Content Hub tag list or don't have path assigned.
Relates to #391
Test URLs:
Before: https://main--hlx-test--urfuwo.hlx.live/news/2020/02/sap-proaxia-intelligent-enterprise-solution-automotive-retail-sap-s-4hana
After: https://feat-500-tagfilter--hlx-test--urfuwo.hlx.live/news/2020/02/sap-proaxia-intelligent-enterprise-solution-automotive-retail-sap-s-4hana
> chore: fix article tag cloud and filter internal tags

- aemedge/blocks/content-list/content-list.css
This is a quick fix specifically for content list as this is causing a spacing issue on the main homepage.
Ideally we need to rework how we apply spacing to the sections and blocks in hub and article pages so that it is more generic and  individual blocks don't have to worry about specifying vertical margin/padding. We can address this on a more after we receive feedback from Elaine, with more explicit rules defined as to how spacing should be applied between elements.
Note: Content list currently a bit broken as tagging changes in progress.
Fix #501
Test URLs:
Before: https://main--hlx-test--urfuwo.hlx.live/topics/
After: https://501-content-list-spacing--hlx-test--urfuwo.hlx.live/topics/
Before: https://main--hlx-test--urfuwo.hlx.live/design/stories-resources/
After: …
> 501: Fix content-list top spacing in sections with background and column sections

- aemedge/blocks/article-tags/article-tags.js
Relates #391 
Test URLs:
After: https://391-taglist--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
> chore: filter content-type from article tag list

- aemedge/scripts/scripts.js
feedback: analytics page name must be prefixed by site name and colon
Fix #522
Test URLs:
Before: https://main--hlx-test--urfuwo.hlx.live/blog/2023/12/being-human-in-the-age-of-ai
After: https://522-analytics-validation-feedback-iteration-1--hlx-test--urfuwo.hlx.live/blog/2023/12/being-human-in-the-age-of-ai
Validation: Append ?tr to the after URL, reload the page. Wait 3s for Launch to run. Execute in console: adobeDataLayer.getState() > inspect DL: page > name . Must be prefixed by sap: (see below)
> Analytics feedback: Prefix page name with site name and colon

- aemedge/scripts/scripts.js
In the data layer, do not prefix the page name with site name and colon
Fix #531 
Test URLs:
After: https://531-analytics-pagename-logic--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
Validation:
* Add ?tr to the URL to enable Analytics for this (DEV) domain, in browser console: adobeDataLayer.getState() > inspect page > name. Must not have a "sap:" prefix. The path name must only contain the (absolute) path, e.g. "/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications"
> Revert data layer page name computation logic

- aemedge/blocks/when-to-use/when-to-use.css
- aemedge/styles/styles.css
- tools/sidekick/library.html
- tools/sidekick/plugins/blocks/design-system.css
- tools/sidekick/plugins/blocks/design-system.js
Fix #513
- Added the new "When To Use" block in code and library
- ❗ Made some changes to general link handling in `styles.css` based on [Frontify](https://sap.frontify.com/document/223142#/-/links) > @saurabh-khare Please have a look
- Added Design System to the Sidekick library @alexcarol (link to Sidekick library does not work yet)
Test URLs:
Before: https://main--hlx-test--urfuwo.hlx.page/topics/
After: https://513-when-to-use--hlx-test--urfuwo.hlx.page/topics/ (focus on the links, nothing changed)
**Design system:**
Before: https://main--hlx-test--urfuwo.hlx.live/fiori-design-web/button-web-component
After: https://513-when-to-use--hlx-test--urfuwo.hlx.page/fiori-design-web/button-web-component
Block Name    | Documentation | …
> 513 when to use

- aemedge/blocks/toc/toc.css
- aemedge/blocks/toc/toc.js
- aemedge/templates/article/article.css
Make TOC sticky for mobile. Added additional event handling to close menu on click outside/esc/focus out
Fix #491
Test URLs:
Before: https://main--hlx-test--urfuwo.hlx.live/draft/rjwtrmn/the-article-copy
After: https://491-sticky-toc-mobile--hlx-test--urfuwo.hlx.live/draft/rjwtrmn/the-article-copy
> 491: TOC sticky in mobile view

- aemedge/blocks/hero/hero.js
Fix #536, #537
Test URLs:
Before: https://main--hlx-test--urfuwo.hlx.live/news/2023/12/ai-powered-startup-partner-solutions-sap-io
After: https://537-news-hero-tag--hlx-test--urfuwo.hlx.live/news/2023/12/ai-powered-startup-partner-solutions-sap-io
Before: https://main--hlx-test--urfuwo.hlx.live/blogs/2023/09/sap-new-zealand-rugby-honor-old-traditions-digitalize-for-the-future
After: https://537-news-hero-tag--hlx-test--urfuwo.hlx.live/blogs/2023/09/sap-new-zealand-rugby-honor-old-traditions-digitalize-for-the-future
> chore: implement generic news center "tag" for hero
